# 文件路径
# 如果是目录,只遍历当前目录下的文件
# 简单支持目录下文件匹配,如:/home/z*.txt,home/test/*.html
# 文件采集单个文件不可大于(Integer.MAX_VALUE - 8)字节
paths:
# 文件采集模式lazy(路径启动时解析),active(调度解析,如监视的目录运行中增加文件)[区分大小写]
# 默认lazy
mode: lazy
# 线程数,默认cpu核数
threads:
# 查探间隔,默认5秒
interval:
